# Project information
site_name: Hongjp's Blog
site_description: 笔录记忆
site_author: Hong jinpin
site_url: https://hongjinpin.com

# Repository
repo_name: Github
repo_url: https://github.com/hongjinpin/hongjinpin.github.io
remote_branch: master
edit_uri: ''

nav:
  - 首页: index.md
  - kubernetes:
      - rancher: kubernetes/rancher.md
  - 随记:
      - certbot: 随记/certbot.md
  - mac:
      - 常用软件: mac/常用软件.md
markdown_extensions:
  - admonition
  # - codehilite:
  #     linenums: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: True
      separator: "_"
extra:
  #  Close how the site was generated.
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: 'https://github.com/hongjinpin'
theme:
  #  custom_dir: material
  name: material
  icon:
    repo: fontawesome/brands/github
  logo: images/logo.jpg
  language: zh
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.footer # 显示上一页下一页
    - navigation.top # 一键回顶部
#    - navigation.tabs